#%RAML 1.0
title: Retrive-RoutesAndSchedules-System

uses:
  common: /Libraries/Common/Common-HeadersLibrary.raml

/{transportType}:
  /{transportCompany}:
    /routes:
      get:
        is: common.transactionId
        responses:
          200:
            body:
              application/json:
                type: array
                items:
                  type: object
                  properties:
                    departureLocationCode:
                      required: true
                      type: string
                      example: "BEN-SG"
                    arrivalLocationCode:
                      required: true
                      type: string
                      example: "KLG-MY"
    /schedules:
          get:
            is: common.transactionId
            queryParameters:
              departureLocationCode:
                required: false
                type: string
                example: "BEN-SG"
              destinationLocationCode:
                required: false
                type: string
                example: "KLG-MY"
            responses:
              200:
                body:
                  application/json:
                    type: array
                    items: 
                      type: object
                      properties:
                        availableSeats:
                          required: true
                          type: number
                          example: 20
                        departureDateTime:
                          required: true
                          type: string
                          example: "2024-11-06T16:41:41.090Z"
                        fromLocation:
                          required: true
                          type: string
                        ToLocation:
                          required: true
                          type: string

                            

                      
                  
                    
                            
                  

